### ISSUE TITLE
[Show Page] Inline images for Show Description need correct padding

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#118]
**Describe the bug**
Inline images in the Show Description have correct padding in the Edit view, but not the front-end view of the Show Page. See screenshots.

**To Reproduce**
1. Go to Show Edit view
2. Add image inline
3. View correct padding (whitespace) around image
4. Save
5. Go to Show Page
6. View incorrect padding around image

**Expected behavior**
When the user adds an image to the Show Description, it should have the same white space applied to it that displays in the edit view.

**Screenshots**

<img width="254" alt="Screen Shot 2020-01-06 at 8 06 09 AM" src="https://user-images.githubusercontent.com/4053819/71820055-eb88f500-305b-11ea-9189-5c7f92166b49.png">
<img width="199" alt="Screen Shot 2020-01-06 at 8 05 16 AM" src="https://user-images.githubusercontent.com/4053819/71820056-eb88f500-305b-11ea-89bb-5fa8e4945c5b.png">

**Comment by majick777** [comment]
Not sure if this is a plugin issue or just WordPress itself... did you specifically add padding anywhere?

**Comment by tonyzeoli** [comment]
No, I did not add any padding anywhere. It may be a holdover from Nikki's code. We're using the base twenty twelve theme with no modifications, so not sure why this is an issue on the front end.

**Comment by majick777** [comment]
Hmmm this may have been a theme issue with the twenty twelve theme, seems to be fine since you switched to Make on the demo site (see Show 9.)

**Comment by majick777** [comment]
Could be retested on twenty twelve at some point to confirm that was the source of the issue.

**Comment by tonyzeoli** [comment]
Tested in Twenty Twelve and still looks like an issue. Twenty Twelve is on now if you want to take a look.

**Comment by majick777** [comment]
Erk weird. I just checked and this doesn't happen with 2010 or 2011, but does with 2012-2015 themes.
Not sure if we should fix or not... I guess adding a targeted style wouldn't hurt, it's rather surprising there is no padding by default in these default themes.

**Comment by tonyzeoli** [comment]
That's strange. I would certainly add that targeted style so people aren't surprised by that and don't know the answer to why that doesn't display on the front end when it does on the backend.

**Comment by tonyzeoli** [comment]
@majick777 Just following up on this open ticket.

**Comment by tonyzeoli** [comment]
@majick777 looks like this is fixed, is that correct? I see in the description field in the latest 2.3.0 beta that this looks fixed.

**Comment by majick777** [comment]
Nope this is not fixed. I'm finding it really hard to reproduce. Even to come up with the same result as I did before... From what I can tell,  seems Add Media adds a `<picture>` tag in newer WP versions and an `<img>` tag in older versions. 

In any case, the image alignment seems to create the padding, so an image with alignnone class does not seem to have it, whereas left and right alignments do. I'm not sure how to make further headway on this one until it can be further tested and reliably reproduced.

**Comment by tonyzeoli** [comment]
Okay, let's close this then. Seems like you are aware of the root cause and solution, so if anyone were to ask it would be an alignment issue that's easily solved by clicking the align left, middle, or right functions.
