### ISSUE TITLE
PHP Errors since release 2.2.1

### ISSUE THREAD

**Issue by thisisshuffle** [netmix/radio-station#14]
Since updating plugin to 2.2.1 php errors are appearing.

The current on-air widget is showing :

> Warning: filemtime(): stat failed for /var/sites/t/thisisshuffle.co.uk/public_html/wp-content/themes/hitmag/djonair.css in /var/sites/t/thisisshuffle.co.uk/public_html/wp-content/plugins/radio-station/includes/widget_djonair.php on line 289

The next on-air widget is adding numbers next to the show title such as

> Through The Night1563580800, 12:00 am-6:00 am

I am on version 5.2.2–en_GB using Hitmag theme

The page I need help with: http://thisisshuffle.co.uk/

**Comment by tonyzeoli** [comment]
Thank you for submitting this bug. We expect to get this fixed asap. Will keep this issue updated.

**Comment by majick777** [comment]
Thanks @thisisshuffle a typo in the logic there, has been fixed for the next release.

**Comment by thisisshuffle** [comment]
Having downloaded update Version 2.2.2. The PHP errors are still showing
![radio-stat-capture](https://user-images.githubusercontent.com/53148877/62159331-5a259200-b309-11e9-9b70-e87fff5b023b.JPG)

**Comment by majick777** [comment]
@thisisshuffle This has been fixed in 2.2.3 just released. :-)
