### ISSUE TITLE
Add Schedule Override - "Override Schedule time/date empty"

### ISSUE THREAD

**Issue by RH233210** [netmix/radio-station#453]
**Describe the bug**
Add Schedule Override - "Override Schedule time/date empty" - Unable to select dates or times in the field 

**To Reproduce**
1. Go to Radio Station 
2. Click on Schedule Override 
3. See error

**Expected behavior**
Time and Date show to select when the override is required

**Screenshots**
![image](https://user-images.githubusercontent.com/30216618/235320244-108d3003-1c24-498c-8146-1e5b6f999ff6.png)

In Previous version it looked like this (roll-backed and its works again)-
![image](https://user-images.githubusercontent.com/30216618/235320587-142d4ee0-2cb9-441d-9474-eaff1bd51efc.png)

**Desktop (please complete the following information):**
Windows, Edge browser, chrome and Firefox

**Smartphone (please complete the following information):**
 n/A

**Additional context**
Since Dev 2.4.9.9 and now live 2.5 this issue is apparent. ( tested latest DEV just incase)

**Comment by tonyzeoli** [comment]
@RH233210 we just released 2.5.1. Please take the update and check if this fixes the issue.

**Comment by RH233210** [comment]
Hi, just updated and issue is still apparent for schedule overrides.

(earlier Dev versions were fine, the latest Dev and Prod are showing the issue) 

Regards
Reece

**Comment by tonyzeoli** [comment]
We just pushed 2.5.2 to resolve Schedule Overrides issues. Please check your WordPress Dashboard and take the latest version. Let us know if that resolves the issue.

**Comment by tonyzeoli** [comment]
Closing this for now.

**Comment by RH233210** [comment]
Hi, I Just updated and the issue is still there. existing override and a brand new one?

Still doesn't give a box to fill in date / time

**Comment by samsmette** [comment]
Hi, this is not working for me either.

We are using version 2.5.2.

![image](https://github.com/netmix/radio-station/assets/68827319/db2aae1a-2b4b-4b04-ae1e-7d626c356774)

**Comment by tonyzeoli** [comment]
Ugh...so sorry. @majick777 please let @samsmette know what the issue could be here.

@samsmette We did just push into the Develop area 2.5.3, which fixes more issues with Schedule Overrides. Please try that under the Develop tab under Code in Github.

**Comment by RH233210** [comment]
This is now resolved as of 2.5.3, I can add overrides in.

**Comment by RH233210** [comment]
This is now resolved as of 2.5.3, I can add overrides in.
