### ISSUE TITLE
Persistent Help support us to make improvements banner...

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#501]
**Describe the bug**
I am working on a client site and I've got a persistent banner on the WP Admin pages - every single one. Pressing the X does not clear it.

I do not have this on my own site (which is running Pro)

**To Reproduce**
Log into any WP admin page

**Expected behavior**
Be able to clear this banner

**Screenshots**
<img width="1327" alt="Image" src="https://github.com/user-attachments/assets/0f605536-460c-494c-8fde-e2cec7989066" />

**Additional context**
Radio Station Version 2.5.9 (free)

**Comment by tonyzeoli** [comment]
@majick777 assigned...please assist Alex, thanks.

**Comment by majick777** [comment]
@astevens93 Hi Alex, I believe this was already fixed in the development version, please install that to verify:
https://github.com/netmix/radio-station/tree/develop/

**Comment by astevens93** [comment]
Hi @majick777 I've installed Version 2.5.9.7 and the banner still persists I'm afraid. 
I'm running Version 2.5.9 on my own site and it's not an issue (though it's got the Pro add on).
Cleared cache too.

**Comment by tonyzeoli** [comment]
You may try to delete the site cookie from your browser and see if that
helps. It may be stored in the cookie and not the cache. I’m not sure but
offering the suggestion in the interim while looking into it further.

**Comment by majick777** [comment]
@astevens93 So turns out there was a period point out of place, which was mangling the link URL on the close icon by duplication (appending to itself,) I've updated the development version with these changes and it works fine again now... So use the latest development version again and I'll close out this issue as resolved.

**Comment by astevens93** [comment]
Thanks @majick777 version 2.5.9.11 resolves the problem
